# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799e2333efd4c2ea0fa8285755e8f8691ceeb3f94fd3078df8707b12b7f34f03622c1be3258a46ec6fd4bfc92419d0ab426282d81e2d0fab95218f2cfba2b8f6

test:
  secret_key_base: 683d59d44eaed3a035d7f514d8bb4c019367c861b74d65862ae513ba56d24b033a9239340445951e56fad29965ad6e55b1731c1ba5380b0f1f02601870a9f924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
